import "./globals.css";
import Sidebar from "@/components/Sidebar";


export const metadata = {
  title: "My Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <div className="flex h-screen">
        <Sidebar />
      <main className="flex-1 ">{children}</main>
        </div>
      
      </body>
    </html>
  );
}
